// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: validation_codes.sql

package tutorial

import (
	"context"
)

const countValidationCode = `-- name: CountValidationCode :one
SELECT count(*) FROM validation_codes WHERE email = $1
`

func (q *Queries) CountValidationCode(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidationCode, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createValidationCode = `-- name: CreateValidationCode :one
INSERT INTO validation_codes (
  email, code
) VALUES (
  $1, $2
)
RETURNING id, code, email, used_at, created_at, updated_at
`

type CreateValidationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) CreateValidationCode(ctx context.Context, arg CreateValidationCodeParams) (ValidationCode, error) {
	row := q.db.QueryRowContext(ctx, createValidationCode, arg.Email, arg.Code)
	var i ValidationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findValidationCode = `-- name: FindValidationCode :one
SELECT id, code, email, used_at, created_at, updated_at FROM validation_codes 
WHERE
  email = $1 
  AND
  code = $2 
  AND
  used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindValidationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) FindValidationCode(ctx context.Context, arg FindValidationCodeParams) (ValidationCode, error) {
	row := q.db.QueryRowContext(ctx, findValidationCode, arg.Email, arg.Code)
	var i ValidationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
